apiVersion: v1
kind: Service
metadata:
  name: vgmlabs-spring-redis-app-service
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000
  selector:
    application: vgmlabs-spring-redis-app