apiVersion: v1
kind: Service
metadata:
  name: vgmlabs-spring-redis-app-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8000
  selector:
    application: vgmlabs-spring-redis-app